apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: subs-nginx
  namespace: nginx-demo
  labels:
    app: nginx-app-subs
  annotations:
    apps.open-cluster-management.io/github-path: app
spec:
  channel: nginx-demo/predev-ch
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-cluster
