apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: subs-nginx
  namespace: nginx-demo
  labels:
    app: nginx-app-subs
spec:
  channel: nginx-demo/predev-ch
  name: nginx-ingress
  packageFilter:
    version: "1.20.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-cluster
